export const courseCategories = [
    { id: 1, name: "Development", icon: "💻", courses: 15, route: "development" },
    { id: 2, name: "Business", icon: "💼", courses: 12, route: "business" },
    { id: 3, name: "Finance & Accounting", icon: "📊", courses: 8, route: "finance-accounting" },
    { id: 4, name: "IT & Software", icon: "🖥️", courses: 10, route: "it-software" },
    { id: 5, name: "Office Productivity", icon: "📁", courses: 7, route: "office-productivity" },
    { id: 6, name: "Personal Development", icon: "🌱", courses: 9, route: "personal-development" },
    { id: 7, name: "Design", icon: "🎨", courses: 6, route: "design" },
    { id: 8, name: "Marketing", icon: "📣", courses: 8, route: "marketing" },
    { id: 9, name: "Lifestyle", icon: "🏖️", courses: 5, route: "lifestyle" },
    { id: 10, name: "Photography & Video", icon: "📷", courses: 7, route: "photography-video" },
    { id: 11, name: "Health & Fitness", icon: "🏋️‍♂️", courses: 4, route: "health-fitness" },
    { id: 12, name: "Music", icon: "🎵", courses: 5, route: "music" },
    { id: 13, name: "Teaching & Academics", icon: "📚", courses: 6, route: "teaching-academics" },
];